### ISSUE TITLE
有时会修改失败

### ISSUE THREAD

**Issue by mlrsyz** [dingguotu/ddns-aliyun#3]
LocalIP is 219.140.112.229
ZgQjjJkkvURdvk9H8rvQtVhRMtA=
HXg782lAbT15UJUIzYEnRLvckck=
Begin update [api.yocu.top].
S2fhkHU+AEoxLWVKwdvqQXkLHgg=
uHc43OhnMM7s/O2M6uHFwZxj4q4=
HTTP Error 400: Bad Request
CxgONgTQC/WAZLAZq0/S8NqHTRc=
Begin update [yz.yocu.top].
uO9a//aKrm8XaiLOpmwiEgyOPBA=
t+kwSEAk9Fmx1cJayFgZZ1lufsA=
HTTP Error 400: Bad Request
rMm8MYd97n9q4YuIS8+Agwn/PcU=
Begin update [gogs.yocu.top].
q5b+lYEc4f+dRf87DrwYhvSBKEk=
kpmRXUNZq5Nt/2OzM2kEozBtPaI=
HTTP Error 400: Bad Request
hDB0yPeJOTb3KDBsKvzyuit2Nv4=
Begin update [mirrors.yocu.top].
pPDXvZoUsr7xkWZbP4UbrgMOQbg=
qxsLVfCfe0/NkjQLj5PuUMkXqEo=
HTTP Error 400: Bad Request

有时去修改阿里的域名配置的时候为什么会是400?   也确实没有修改好,  我把阿里的解析删了在执行一次是可以添加上去的
可以看一下这个问题吗?   谢谢   如果不行我就去找一下类似的脚本   感谢了

**Comment by dingguotu** [comment]
感谢提Issue，这两天公司有点忙，没顾得上，问题已经解决，可以放心使用了
