### ISSUE TITLE
IP获取的API炸掉了

### ISSUE THREAD

**Issue by z0ow** [dingguotu/ddns-aliyun#4]
淘宝ip地址库API返回一律203.119.241.121，无法正常使用了

**Comment by z0ow** [comment]
我暂时将获取ip地址的api改成http://ip-api.com/json 了，如果作者有更好的选择可以考虑更新一下 😄

**Comment by ohyeah521** [comment]
我靠，我5分钟检测一次，然后邮箱炸了，都是阿里云修改ip的邮件

**Comment by ohyeah521** [comment]
这个速度慢点
https://ipapi.co/json/

可以弄3个接口，互相校验

**Comment by dingguotu** [comment]
感谢两位提醒，现在已经更新了获取接口，暂时提供了8个api可供选择，可以只用一个，也可以都用，不过得自己修改源码
