### ISSUE TITLE
新版的代码读取configuration文件处理有误 

### ISSUE THREAD

**Issue by z0ow** [dingguotu/ddns-aliyun#8]
更新代码后始终运行报错，review代码看到ddns.py始终读取conf.sample.json，导致后续流程不能正常运行，建议做一个patch

master中的代码情况： 

https://github.com/dingguotu/ddns-aliyun/blob/daba8f24ba25daed23018ab2557ed39af3c201f6/ddns.py#L66

v1.0.0 版本中的代码情况： 

https://github.com/dingguotu/ddns-aliyun/blob/daba8f24ba25daed23018ab2557ed39af3c201f6/ddns.py#L66

**Comment by dingguotu** [comment]
感谢细心的朋友，确实是我自己的疏忽导致文件名错了，现在已经修复，请继续使用
